### ISSUE TITLE
Feature request: Add a common command prefix to facilitate command/function invocation and selection.

### ISSUE THREAD

**Issue by hongyi-zhao** [goodluck1982/SpaceGroupIrep#34]
I noticed that all the customized commands of `gtpack` are prefixed with `GT`, so I think the similar feature also can be implemented in `SpaceGroupIrep` to facilitate invocation and selection of all commands/functions.

![image](https://user-images.githubusercontent.com/11155854/155072591-40b5137b-9087-48f8-abc6-7666810c4949.png)

A possible change might look like this: `showBZDemo -> SGShowBZDemo`.

Regards,
HZ

**Comment by goodluck1982** [comment]
I admit that a common prefix is a feature of  `gtpack`, but this is not a general convention for coding. It depends on the developer's taste. As for `SpaceGroupIrep`,  because it has been released for more than one year and has related research paper published, it's really a bad idea to change all the function names to make unnecessary troubles for users.

In fact, one can easily know what functions/variables `SpaceGroupIrep` has by 
```Mathematica
?SpaceGroupIrep`*
```
![image](https://user-images.githubusercontent.com/48718961/158314674-1fe63150-c8ec-43dc-9df7-6f20366e7be1.png)
